# Generated by Django 5.0.6 on 2024-07-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_covid_heartdiseases_immunization_mentalhealth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
