# Generated by Django 5.0.6 on 2024-07-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_mentalhealth_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='covid',
            name='image',
            field=models.ImageField(default='', upload_to='Covid/images'),
        ),
        migrations.AddField(
            model_name='heartdiseases',
            name='image',
            field=models.ImageField(default='', upload_to='Heartdiseases/images'),
        ),
        migrations.AddField(
            model_name='immunization',
            name='image',
            field=models.ImageField(default='', upload_to='Immunization/images'),
        ),
    ]
